apiVersion: audit.k8s.io/v1
kind: Policy
omitStages:
  - RequestReceived
  - ResponseStarted
  - Panic
rules:
  - level: Request
    verbs:
      - create
      - patch
    resources:
      - group: ''
        resources:
          - pods
          - pods/exec
          - podtemplates
          - statefulsets
          - replicationcontrollers
          - replicasets
          - deployments
          - statefulsets
          - daemonsets
          - jobs
          - cronjobs
